# Base Debian
FROM debian:bullseye

# Dépendances générales
RUN apt-get update && apt-get install -y \
    curl gnupg wget build-essential ca-certificates lsb-release gnupg2 \
    libssl-dev libffi-dev

# Ajout de la clé GPG MongoDB officielle
RUN curl -fsSL https://pgp.mongodb.com/server-6.0.asc | gpg --dearmor -o /usr/share/keyrings/mongodb-server-6.0.gpg

# Ajout du dépôt officiel MongoDB 6.0 pour Debian
RUN echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/debian bullseye/mongodb-org/6.0 main" \
    > /etc/apt/sources.list.d/mongodb-org-6.0.list

# Installation de MongoDB + AMC + Node.js
RUN apt-get update && apt-get install -y \
    mongodb-org \
    nodejs npm \
    texlive-full \
    auto-multiple-choice \
    && rm -rf /var/lib/apt/lists/*

# Création dossier base Mongo
WORKDIR /app
RUN mkdir -p /app/db

# Copie du projet
COPY . /app

# Installation des modules Node.js
RUN npm install

# Ports exposés
EXPOSE 3000 27017

# Lancement Mongo + serveur Node
CMD ["sh", "-c", "mongod --dbpath ./db --fork --logpath /var/log/mongod.log && node server.js"]
